<a href="https://colab.research.google.com/github/cnyakundi/financial_inclusion/blob/master/notebooks/Multivariate_Analysis_week_3_IP_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Principal Component Analysis




#Importing our libraries 

In [75]:
# Step 1: Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [76]:
#Loading our dataset

df=pd.read_csv('Financial Dataset.csv')

df.head()

country  year  ...              Level of Educuation                Type of Job
0   Kenya  2018  ...              Secondary education              Self employed
1   Kenya  2018  ...              No formal education       Government Dependent
2   Kenya  2018  ...  Vocational/Specialised training              Self employed
3   Kenya  2018  ...                Primary education  Formally employed Private
4   Kenya  2018  ...                Primary education        Informally employed

[5 rows x 13 columns]

## Cleaning our Dataset

In [77]:
# We can convert Cell Phone Access and gender of respondents into categories. This will reduce memory usage 

df['Has a Bank account'].fillna('0')


# df['Cell Phone Access']=df['Cell Phone Access'].astype('category')


df['gender_of_respondent']=df['gender_of_respondent'].astype('category')



#We convert country, unique_id, the relationship with head, marital status, level of education and type of job into strings 

df['year']=pd.to_datetime(df['year']) # Convert date to datetime 
df['country']=df['country'].astype('str')
df['uniqueid']=df['uniqueid'].astype('str')
df['uniqueid']=df['uniqueid'].astype('str')
df['The relathip with head']=df['The relathip with head'].astype('str')
df['marital_status']=df['marital_status'].astype('str')
df['Level of Educuation']=df['Level of Educuation'].astype('str')
df['Type of Job']=df['Type of Job'].astype('str')



# Replace yes and No with '1' amd '0' then cast into integers 

df.replace(to_replace=['Yes','No'],value=['1','0'], inplace=True)


df['Has a Bank account'].fillna('0', inplace=True)


df['Has a Bank account']=df['Has a Bank account'].astype('int')
df.replace(to_replace=['Yes','No'],value=['1','0'], inplace=True)

# Replace yes and No with '1' amd '0' then cast into integers

df['Cell Phone Access'].fillna('0', inplace=True)

df['Cell Phone Access']=df['Cell Phone Access'].astype('int')

# Converting Type of location into integers 

df.replace(to_replace=['Rural','Urban'],value=['0','1'], inplace=True)
df['Type of Location'].fillna('0', inplace=True)

df['Type of Location']=df['Type of Location'].astype('int')

# Dealing with the Missing Data
# df['Respondent Age']=df['Respondent Age'].fillna(df['Respondent Age'].mode())


# df.isnull().sum()


# We fill all these with 0 because many people dont have bank accounts, live in rural areas and dont have cell phone access

df['Has a Bank account'].fillna('0', inplace=True)

df['Type of Location'].fillna('0', inplace=True)

df['Cell Phone Access'].fillna('0', inplace=True)

df.head()

country  ...                Type of Job
0   Kenya  ...              Self employed
1   Kenya  ...       Government Dependent
2   Kenya  ...              Self employed
3   Kenya  ...  Formally employed Private
4   Kenya  ...        Informally employed

[5 rows x 13 columns]

In [78]:
#Dropping columns I wont be using in PCA 

df.drop([
       'gender_of_respondent', 'The relathip with head', 'marital_status',
       'Level of Educuation', 'Type of Job','year', 'uniqueid'], axis =1, inplace=True)



## Previewing my dataset

In [79]:
df.head()



country  Has a Bank account  ...  household_size  Respondent Age
0   Kenya                   1  ...             3.0            24.0
1   Kenya                   0  ...             5.0            70.0
2   Kenya                   1  ...             5.0            26.0
3   Kenya                   0  ...             5.0            34.0
4   Kenya                   0  ...             8.0            26.0

[5 rows x 6 columns]

### Pre-processing 

In [88]:
X = df.drop('country', 1)
y = df['country']

# df['household_size']=df['household_size'].fillna(2.0, inplace=True)

# df['Respondent Age']=df['Respondent Age'].fillna(df['Respondent Age'].mode(), inplace=True)

df.head()
df.dropna(inplace=True)
df.isnull().values.any()


False

###  Splitting the dataset into the Training set and Test set

In [89]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Normalization 

In [90]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Applying PCA

In [91]:
from sklearn.decomposition import PCA

pca = PCA()
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

### Explained Variance Ratio

In [93]:
explained_variance = pca.explained_variance_ratio_

explained_variance 

array([0.26934727, 0.24284865, 0.20394382, 0.15267072, 0.13118953])

 ### Using 1 Principal Component

In [95]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

X_train

array([[-0.07989127],
       [-0.19121972],
       [ 0.73861325],
       ...,
       [-0.37227505],
       [ 1.14858999],
       [-1.39948078]])

### Training and Making Predictions

In [97]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)



array(['Tanzania', 'Rwanda', 'Tanzania', ..., 'Rwanda', 'Tanzania',
       'Rwanda'], dtype=object)

 ### Performance Evaluation

In [98]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' , accuracy_score(y_test, y_pred))

[[   1  854  352    0    0]
 [   1 1574  170    0    0]
 [   1  342  966    0    0]
 [   0  357   72    0    0]
 [   0    1    3    0    0]]
Accuracy 0.5413293566254793


### Results with 2 Principal Components

In [102]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)


array([[-1.77349289e+01, -2.02407545e+00],
       [ 2.42742339e+01, -2.25228572e+00],
       [ 3.52576132e+01, -1.15437949e+00],
       ...,
       [-2.07688774e+01,  2.47453662e-03],
       [ 2.12595832e+01, -1.38411050e+00],
       [ 1.22429601e+01, -4.53743775e-01]])

### Results with 2 Principal Components

In [103]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

pca = PCA(n_components=3)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

# With three principal components the classification accuracy should again increase to 93.33%
classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=2, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

### Predicting the Test set results

In [104]:
y_pred = classifier.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy' , accuracy_score(y_test, y_pred))

[[  14  843  350    0    0]
 [   4 1600  141    0    0]
 [   0  347  962    0    0]
 [   3  349   77    0    0]
 [   0    1    3    0    0]]
Accuracy 0.5487856838517257


### SECTION 2 - Factor analysis 

###  Loading our Dataset

In [105]:
df.head()

country  Has a Bank account  ...  household_size  Respondent Age
0   Kenya                   1  ...             3.0            24.0
1   Kenya                   0  ...             5.0            70.0
2   Kenya                   1  ...             5.0            26.0
3   Kenya                   0  ...             5.0            34.0
4   Kenya                   0  ...             8.0            26.0

[5 rows x 6 columns]

###  Previewing the dataset columns

In [106]:
df.columns

Index(['country', 'Has a Bank account', 'Type of Location',
       'Cell Phone Access', 'household_size', 'Respondent Age'],
      dtype='object')